<a href="https://colab.research.google.com/github/Shivam311201/Beginning-with-AI-ML/blob/master/Libraries/Learning_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import sys
import time

In [4]:
arr = np.array([4,1,2,3])
arr[0]

4

##### Despite having python list, we need numpy array:

1.   Less Memory as python list refer to objects, thus had greater size
2.   Less time and more convenient



In [10]:
a=np.arange(100)
print(a.size*a.itemsize)

a1=range(100)
print(sys.getsizeof(1)*len(a1))

800
2800


In [15]:
size=100000
l1 = range(size)
l2 = range(size)

l3 = np.arange(size)
l4 = np.arange(size)

# Python List
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Time taken: " , (time.time()-start)*1000)

# Numpy List
start=time.time()
result=l3+l4
print("Time taken: " , (time.time()-start)*1000)

Time taken:  15.78974723815918
Time taken:  2.9571056365966797


In [20]:
a3=np.array([1,2,3])
a4=np.array([4,5,6])

print(a3+a4)
print(a3*a4)

[5 7 9]
[ 4 10 18]


In [46]:
ndarray=np.array([[1,2],[3,4],[5,6]])
array2=np.array([[1,2],[3,4],[5,6]])
ndarray.itemsize # byte size of each element

8

In [30]:
print(ndarray.ndim) # Dimension of inner vector
print(ndarray.dtype)
print(ndarray.size)
print(ndarray.shape) # Dimension nxm

2
int64
6
(3, 2)


In [27]:
ndarrayF=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
ndarrayF

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [32]:
aZero=np.zeros((3,4))
aZero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
print(np.arange(1,5))
print(np.arange(1,5,2)) # jump by 2 everytime

[1 2 3 4]
[1 3]


In [35]:
ndarray.shape
ndarray.reshape((2,3)) # Reshape the array into compatible dimensions; doesn't change original array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(ndarray.sum(axis=0)) # Sum along columns
print(ndarray.sum(axis=1)) # Sum along rows

[ 9 12]
[ 3  7 11]


In [37]:
arr = np.array([1,2,3,4])

In [41]:
print(arr[-1]) # print element from reverse
print(arr[1:3])

4
[2 3]


In [45]:
print(ndarray[1,1])
print(ndarray[0:2,1])
print(ndarray[:,1])

4
[2 4]
[2 4 6]


In [49]:
print(np.vstack((ndarray,array2)))
stackedArray=np.hstack((ndarray,array2))

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [50]:
stackedArray

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [51]:
np.hsplit(stackedArray,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]])]

In [52]:
for row in ndarray:
  for col in row:
    print(col)


1
2
3
4
5
6


In [56]:
for x in np.nditer(ndarray,order='C'):
  print(x)

for x in np.nditer(ndarray,order='F',flags=['external_loop']):
  print(x)

1
2
3
4
5
6
[1 3 5]
[2 4 6]


In [57]:
for x,y in np.nditer([ndarray,ndarrayF],order='C'):  # Iterate over array simultaneously
  print(x,y)

1 1.0
2 2.0
3 3.0
4 4.0
5 5.0
6 6.0
